$(".botao__mudar").click(function (e) {
  e.preventDefault();
  mudarFrase();
});
function mudarFrase() {
  let x = Math.floor(Math.random() * frases.length);
  frase.text(frases[x]);
  let tamanhoFrase = frase.text().split(" ").length;
  palavras.text(tamanhoFrase + " ");
  aumentaAreaDeTexto(tamanhoFrase);
}
function fraseAleatoria() {
  mudarFrase();
  k++;
  atFrases.text(k + "");
}
let frases = [
  "Duro como pedra.",
  "Meu braço direito é ainda mais forte que o meu braço esquerdo!",
  "Sou tanto espada quanto escudo!",
  "A dor é temporária, a vitória é eterna.",
  "A paz é a maior mentira da história.",
  "Se você quiser jogar comigo, é melhor conhecer bem o jogo.",
  "A piedade é um luxo e uma responsabilidade dos seres humanos.",
  "Não confunda piedade com fraqueza.",
  "Um coração gelado só precisa de um coração caloroso.",
  "Não importa quanto tempo você tem, mas como você o usa.",
  "As pessoas perdem muito tempo e querem mais. Eles querem mais horas em seus dias, mais dias em seus anos, mais anos em suas vidas.",
  "A única morte verdadeira é nunca ter vivido.",
  "Caçar os fracos e sobreviver, caçar os fortes e viver.",
  "Existem erros que você não pode fazer duas vezes.",
  "Estamos todos indo em direção ao mesmo fim inevitável. Não precisa ter pressa!",
  "A palavra certa corta mais profundamente que uma faca.",
  "O coração é o musculo mais forte.",
  "Toda vida é preciosa! É sim! Até a sua.",
  "Precisão é a diferença entre um açougueiro e um cirurgião",
  "No mundo ninja, aqueles que quebram as regras e as leis são vistos como escória, mas aqueles que abandonam até um de seus amigos são piores que escória.",
  "Saber o que é certo e escolher ignorá-lo é um ato de covardia.",
  "Não é a face que torna alguém um monstro, são as escolhas que você faz com sua vida.",
  "O conceito de esperança não é mais do que desistir. Uma palavra que não contem qualquer significado.",
  "A vida de um shinobi não é medida por como ele viveu, mas pelo que conseguiu atingir antes de morrer.",
  "Por vezes você precisa de sofrer para saber, cair para crescer, perder para ganhar porque a maiores lições na vida são aprendidas através da dor.",
  "Antes, quando lutava sentia tantas emoções dentro de mim. Medo, pânico, raiva. Mas agora eu posso terminar tudo em apenas um golpe.",
  "Estou disposto a fazer qualquer coisa para me tornar mais poderoso. No entanto, não consigo me imaginar chegando mesmo perto de alcançar o poder do sensei.",
  "Não importa se eu tiver uma chance ou não! Eu tenho que lutar contra você aqui e agora!",
  "Eu não temo a morte. Eu só temo que minha raiva desapareça.",
  "Não julgue quem você é, apenas aceite, se você quer mudar e ser uma pessoa melhor, terá que aceitar quem você já foi.",
  "Eu amo lutar, mas mais do que isso, eu odeio perder! Eu só luto para vencer!",
  "Peço a terra, ao céu ao mar, que me deem um pouco de sua energia, não estou pedindo para mim. Faço isso pelo bem de todos.",
  "Uma chance num milhão é melhor que nenhuma chance!",
  "Por que motivo as garotas têm bundas no peito?",
  "Nem todos os que vagueiam estão perdidos.",
  "A irmandade deve prevalecer.",
  "Obedeçam ao meu comando.",
  "Não posso esperar mais.",
  "Você venceu, mas seu mundo continua condenado.",
  "Que a serpente de jade guie você.",
  "Temos sede de vingança.",
  "Prepare-se para a fúria de Millhouse.",
  "Eu posso ficar aqui esperando o dia todo.",
  "Agora é para valer.",
  "O lugar disso é no museu.",
  "Tenha coragem, a Mãe Terra está chamando.",
  "Você não está preparado.",
  "Com licença, o senhor está pegando fogo.",
  "Eu sou a essência da magia.",
  "Vem todo mundo para cá!",
  "Você quer comprar bolo de fubá?",
  "A natureza se levantará contra você!",
  "Que a caçada comece!",
  "Minha magia despedaçará você!",
  "A luz protege aqueles que dela fazem uso.",
  "A luz sorri para os justos!",
  "Tempestade, terra e fogo, ouçam meu chamado!",
  "Eu sou seu pesadelo!",
  "Vitória ou morte!",
  "Eu vejo gente morta.",
  "Dadinho é o caralho, meu nome é Zé Pequeno, porra!",
  "Francamente, minha querida, eu não dou a mínima.",
  "Tantos bares, em tantas cidades em todo o mundo, e ela tinha que entrar logo no meu?",
  "A vida é como uma caixa de chocolates. Você nunca sabe o que vai encontrar.",
  "Grandes poderes trazem grandes responsabilidades.",
  "Mantenha os seus amigos por perto, e os inimigos ainda mais perto.",
  "Que a força esteja com você!",
  "Ou você morre herói, ou vive o suficiente para se tornar o vilão.",
  "O ontem é história, o amanhã é um mistério, mas o hoje é uma dádiva. É por isso que se chama presente.",
  "Nunca desista, encontre um jeito, pois é assim que fazem os vencedores.",
  "Capacidade de falar não é sinal de inteligência!",
  "Os pequenos detalhes são sempre os mais importantes.",
  "Você não pode exigir a resposta certa se fizer a pergunta errada.",
  "Nada acontece duas vezes da mesma maneira.",
  "As competições revelam nossas fraquezas e inflam o ego…Nossos verdadeiros inimigos somos nós mesmos.",
  "Se prestarmos bastante atenção, sempre conseguiremos descobrir alguma compensação no sofrimento.",
  "Ser vilão nem sempre é querer o mal, mas sim ter um pensamento diferente dos que acham estar fazendo o bem.",
  "Paramos de procurar monstros embaixo da nossa cama quando percebemos que eles estão dentro de nós.",
  "Faça seus medos terem medo de você.",
  "Para ser um guerreiro, não se deve apenas empunhar uma espada. Deve-se ter uma razão pela qual empunhá-la.",
  "As pessoas temem o que não entendem.",
  "Viver é como andar de bicicleta. Se parar, cai.",
  "Só quando perdemos tudo, é que estamos livres pra fazer qualquer coisa.",
  "Eu faço o povo rir, mas quem é que vai me fazer rir?",
  "Penso que quando formos cada um para o seu lado, poderíamos ir para os mesmos lados juntos.",
  "Você mentiu para mim dizendo a verdade.",
];
